import React, { useEffect, useState } from 'react';
import { ArrowRight, CalendarDays, Check, ChevronDown, Clock3, ExternalLink, Menu, MessageCircle, Phone, Quote, ShieldCheck, Sparkles, Star, X, ZoomIn } from 'lucide-react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { business, gallery, nav, services } from './data';
gsap.registerPlugin(ScrollTrigger);
const wa=`https://wa.me/${business.whatsapp}`;
const maps=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(business.address)}`;
const SITE_OFFLINE=true;

function Stars(){return <span className="stars" aria-label="5 out of 5 stars">{[1,2,3,4,5].map(i=><Star key={i} size={17} fill="currentColor"/>)}</span>}
function Header(){const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false); useEffect(()=>{const f=()=>setScrolled(scrollY>30); addEventListener('scroll',f,{passive:true}); return()=>removeEventListener('scroll',f)},[]); return <header className={scrolled?'nav scrolled':'nav'}><a href="#home" className="logo"><span>S</span> STYLORA</a><button className="menu-btn" onClick={()=>setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''} aria-label="Main navigation">{nav.map(x=><a key={x} href={`#${x.toLowerCase()}`} onClick={()=>setOpen(false)}>{x}</a>)}<a href="#booking" className="nav-cta">Book appointment</a></nav></header>}
function SectionTitle({eyebrow,title,copy}){return <div className="section-head reveal"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
function App(){
  const [lightbox,setLightbox]=useState(null); const [feedback,setFeedback]=useState('');
  useEffect(()=>{const ctx=gsap.context(()=>{gsap.utils.toArray('.reveal').forEach(el=>gsap.fromTo(el,{y:45,opacity:0},{y:0,opacity:1,duration:.9,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}}))}); return()=>ctx.revert()},[]);
  const submit=e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const vals=Object.fromEntries(fd); if(!vals.name||!vals.phone||!vals.service||!vals.date||!vals.time){setFeedback('Please complete all required fields.');return} const msg=`Hello Stylora Unisex Salon, I would like to book an appointment.\n\nName: ${vals.name}\nPhone: ${vals.phone}\nService: ${vals.service}\nPreferred date: ${vals.date}\nPreferred time: ${vals.time}\nMessage: ${vals.message||'—'}`; setFeedback('Your details are ready. Opening WhatsApp…'); window.open(`${wa}?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer')};
  if(SITE_OFFLINE) return <main className="offline-page"><div className="offline-mark">S</div><p>Stylora Unisex Salon</p><h1>We’ll be back soon.</h1><span>This website is temporarily offline.</span></main>;
  return <><Header/><main>
    <section id="home" className="hero panel"><div className="hero-glow"/><div className="hero-copy"><span className="eyebrow">Premium unisex salon · Muvattupuzha</span><h1><i>Style</i> That<br/>Defines You</h1><p>Modern grooming, hair and beauty care—shaped around you in a space designed for comfort.</p><div className="actions"><a className="btn gold" href="#booking"><CalendarDays/>Book an appointment</a><a className="btn ghost" href={`tel:${business.phone}`}><Phone/>Call now</a></div><div className="rating"><Stars/><span><b>{business.rating}</b> rating from {business.reviews} customer reviews</span></div></div><a href="#services" className="scroll-cue">Discover <ChevronDown/></a><div className="hero-index">01 <span/> 06</div></section>
    <section id="services" className="section panel services"><SectionTitle eyebrow="The Stylora Edit" title="Care, cut and craft." copy="Considered salon services for every expression of you. Contact us for pricing."/><div className="service-grid">{services.map(([name,desc,Icon],i)=><article className="service-card reveal" key={name}><span className="num">0{i+1}</span><Icon/><h3>{name}</h3><p>{desc}</p><a href={`${wa}?text=${encodeURIComponent(`Hello Stylora Unisex Salon, I would like to enquire about ${name}.`)}`} target="_blank" rel="noreferrer">Enquire now <ArrowRight/></a></article>)}</div></section>
    <section id="about" className="section panel about"><div className="about-copy"><SectionTitle eyebrow="About Stylora" title="Your look. Our full attention."/><p className="lead reveal">Stylora is a modern grooming and beauty destination in Muvattupuzha, created for men and women who value personal care and thoughtful styling.</p><p className="reveal">From consultation through the finishing touch, our focus is simple: understand your preference, prioritise your comfort and deliver professional care in a hygienic environment using quality salon products.</p><div className="feature-lines reveal"><span>01 — Personalised service</span><span>02 — Modern styling</span><span>03 — Professional care</span></div></div></section>
    <section className="why section"><SectionTitle eyebrow="The difference" title="Why guests choose Stylora."/><div className="why-grid">{[['45','Five-star customer reviews'],['5.0','Overall customer rating'],['All','Services for men & women'],['Near','Convenient MC Road location']].map(([n,t])=><div className="stat reveal" key={t}><strong>{n}</strong><span>{t}</span></div>)}</div><div className="trust-row reveal">{['Professional styling','Personalised consultations','Hygienic environment','Quality salon products'].map(x=><span key={x}><Check/>{x}</span>)}</div></section>
    <section id="gallery" className="section panel gallery"><SectionTitle eyebrow="The lookbook" title="Designed to inspire." copy="A curated glimpse of modern cuts, colour, grooming, beauty and salon style."/><div className="gallery-grid">{gallery.map((g,i)=><button className={`gallery-item item-${i+1} reveal`} key={g.src} onClick={()=>setLightbox(g)} aria-label={`View ${g.alt}`}><img src={g.src} alt={g.alt} loading="lazy"/><span>{g.cat}<ZoomIn/></span></button>)}</div></section>
    <section id="reviews" className="section panel reviews"><div className="review-card reveal"><Quote/><span className="eyebrow">Customer confidence</span><div className="big-rating">5.0</div><Stars/><h2>45 reviews. Every one five-star.</h2><p>Real customer quotations are not shown because testimonial text was not supplied. The verified rating summary stands on its own.</p><div className="verified"><ShieldCheck/> Rating information provided by the business</div></div></section>
    <section id="booking" className="section panel booking"><div className="booking-intro"><SectionTitle eyebrow="Your next look" title="Reserve your moment." copy="Share your preferences and continue directly in WhatsApp. The salon will confirm availability with you."/><div className="mini-contact reveal"><Clock3/><span>Opening hours<br/><b>Contact the salon for current hours</b></span></div></div><form className="booking-form reveal" onSubmit={submit} noValidate><label>Your name *<input name="name" autoComplete="name" required placeholder="Enter your name"/></label><label>Phone number *<input name="phone" type="tel" autoComplete="tel" required placeholder="Your contact number"/></label><label>Service *<select name="service" required defaultValue=""><option value="" disabled>Select a service</option>{services.map(([x])=><option key={x}>{x}</option>)}</select></label><div className="form-row"><label>Preferred date *<input name="date" type="date" required min={new Date().toISOString().split('T')[0]}/></label><label>Preferred time *<input name="time" type="time" required/></label></div><label>Message<textarea name="message" rows="3" placeholder="Anything you would like us to know?"/></label><button className="btn gold" type="submit"><MessageCircle/>Continue in WhatsApp</button><p className="feedback" role="status">{feedback}</p></form></section>
    <section id="contact" className="contact section"><SectionTitle eyebrow="Find us" title="Closer than you think."/><div className="contact-grid"><div><h3>{business.name}</h3><p>{business.address}</p><p className="hours">Contact the salon for current opening hours.</p></div><div className="contact-actions"><a href={`tel:${business.phone}`} className="btn ghost"><Phone/> {business.phoneDisplay}</a><a href={wa} target="_blank" rel="noreferrer" className="btn gold"><MessageCircle/>WhatsApp</a><a href={maps} target="_blank" rel="noreferrer" className="btn ghost"><ExternalLink/>Directions</a></div></div></section>
  </main><footer><a href="#home" className="logo"><span>S</span> STYLORA</a><p>A modern unisex salon for personalised grooming, hair and beauty care in Muvattupuzha.</p><div className="footer-links">{nav.map(x=><a href={`#${x.toLowerCase()}`} key={x}>{x}</a>)}</div><div className="social-note">Social media links coming soon.</div><small>© {new Date().getFullYear()} Stylora Unisex Salon. All rights reserved.</small></footer>
  <a href={wa} className="float-wa" target="_blank" rel="noreferrer" aria-label="Chat with Stylora on WhatsApp"><MessageCircle/></a>
  {lightbox&&<div className="lightbox" role="dialog" aria-modal="true" aria-label={lightbox.alt} onClick={()=>setLightbox(null)}><button aria-label="Close image"><X/></button><img src={lightbox.src} alt={lightbox.alt}/><span>{lightbox.alt}</span></div>}</>;
}
export default App;
